apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  namespace: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: karolswidrak/app2:v2.0.8
        ports:
        - containerPort: 8010
        env:
          - name: RABBITMQ_HOST
            value: "rabbitmq.kong.svc.cluster.local"
          - name: RABBITMQ_PORT
            value: "5672"
          - name: REDIS_HOST
            value: "redis-master.kong.svc.cluster.local"
          - name: REDIS_PORT
            value: "6379"
