apiVersion: v1
kind: Service
metadata:
  name: app3-svc
  namespace: kong
  labels:
    app: app3-svc
spec:
  ports:
  - port: 8010
    targetPort: 8010
    name: http
    protocol: TCP
  selector:
    app: app3