name: Build and Test
on: [push]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app2/requirements.txt
    - name: Start Redis
      uses: supercharge/redis-github-action@1.4.0
      with:
        redis-version: 7.0
    - name: Start RabbitMQ
      uses: namoshek/rabbitmq-github-action@v1
      with:
        version: '3.8.9'
        ports: '5672:5672'
        certificates: ${{ github.workspace }}/.ci/tls-certificates
        config: ${{ github.workspace }}/.ci/rabbitmq.conf
        definitions: ${{ github.workspace }}/.ci/definitions.json
        container-name: 'mqtt'
    - name: Test
      run: |
        python -m venv env
        . env/bin/activate
        cd app2/api_get
        pytest tests.py
