name: Build and Test
on: [push]
jobs:
  ci-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.0
          cache: 'pip'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run flake8
        run: flake8
      - name: Run pytest
        run: pytest tests
